source 'https://rubygems.org/'

gem 'docker-api'

group :test do
  gem 'ffi'
  gem 'net-telnet', '>= 0.2.0'
  gem 'specinfra'
  gem 'net-ssh'
  gem 'serverspec'
  gem 'itamae'
  gem 'selenium-webdriver'
end
