version: '3.2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
      - 127.0.0.1:11478:11478

  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - type: bind
        source: ./dist-docs/sample_schema_mysql.sql
        target: /docker-entrypoint-initdb.d/sample_schema_mysql.sql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: im4135dev
      MYSQL_USER: web
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 127.0.0.1:3306:3306