# -*- mode: ruby -*-
# vi: set ft=ruby :

# If provisioning by Itamae, it is necessary to install vagrant-itamae and Itamae.
# $ vagrant plugin install vagrant-itamae
# $ gem install itamae

Vagrant.configure(2) do |config|
  config.vm.box = "INTER-Mediator-Server-Ubuntu-18.04"
  config.vm.box_url = "https://inter-mediator.com/archives/INTER-Mediator-Server-Ubuntu-18.04.5.box"
  #config.vm.box_url = "https://inter-mediator.com/archives/INTER-Mediator-Server-CentOS-7.8.box"
  #config.vm.box_url = "https://inter-mediator.com/archives/INTER-Mediator-Server-Alpine-Linux-3.13.5.box"
  #config.vm.box_url ="file://./INTER-Mediator-Server-Ubuntu-18.04.5.box"
  #config.vm.network "private_network", ip: "192.168.56.101", auto_config: false
  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  #config.vm.synced_folder 'html/', '/var/www/html'
  #config.vm.hostname = "inter-mediator-server"
  config.vm.post_up_message = "INTER-Mediator-Server VM is ready."
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.memory = "2048"
    vb.name = "INTER-Mediator-Server"
  end

  config.ssh.username = "developer"
  config.ssh.password = "im4135dev"
  config.ssh.pty = true

  ## provisioning by shell script
  config.vm.provision "file", source: "recipe.rb", destination: "$HOME/recipe.rb"
  config.vm.provision "shell", path: "deploy.sh"
  # Testing by msyk's repository file
  #config.vm.provision "shell", path: "https://raw.githubusercontent.com/inter-mediator/INTER-Mediator/master/dist-docs/vm-for-trial/deploy.sh"

  ## provisioning by itamae
  #config.vm.provision :itamae do |config|
  #  config.sudo = true
  #  config.recipes = ['./recipe.rb']
  #end
end
