name: Publish Image

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
    paths:
      - '.github/workflows/Dockerfile_Container'
  workflow_dispatch:

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: '.github/workflows/Dockerfile_Container'
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}