name: run-phpstan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]

jobs:
  run:
    name: Run PHPStan
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        level: [ 1, 2 ]
        include:
          - current-level: 1
    steps:
      - uses: actions/checkout@latest # v4.1.1

      - name: Setup PHP
        uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35 # v2.28.0
        with:
          php-version: '8.2'

      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan
        continue-on-error: true
        if:  matrix.level == matrix.current-level
        run: ./vendor/bin/phpstan analyse -c spec/phpstan.neon --memory-limit 512M src spec/INTER-Mediator-UnitTest --level "${{ matrix.level }}"

      - name: Run PHPStan
        if:  matrix.level > matrix.current-level
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse -c spec/phpstan.neon --memory-limit 512M src spec/INTER-Mediator-UnitTest --level "${{ matrix.level }}"
             exit 0
