name: run-phpstan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ 'master', 'main' ]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    name: Run PHPStan
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup PHP
        uses: shivammathur/setup-php@72ae4ccbe57f82bbe08411e84e2130bd4ba1c10f # v2.25.5
        with:
          php-version: '8.2'

      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan

      - name: Run PHPStan
        continue-on-error: true
        run: |
             ./vendor/bin/phpstan analyse -l 0 --memory-limit 512M src spec/INTER-Mediator-UnitTest
             exit 0
